// ============================================================
// REACHABILITY ENGINE
// ============================================================
//
// Input:
//     Graph generated by graphBuilder.js
//
// Purpose:
//     Determine whether a source can reach a destination.
//
// This file DOES NOT build the graph.
// It only analyzes an existing graph.
// ============================================================


// ============================================================
// CHECK IF SOURCE AND DESTINATION EXIST
// ============================================================

function validateEndpoints(graph, source, destination) {

  if (!graph.hasNode(source)) {
    return {
      valid: false,
      error: `Source not found: ${source}`,
    };
  }

  if (!graph.hasNode(destination)) {
    return {
      valid: false,
      error: `Destination not found: ${destination}`,
    };
  }

  return {
    valid: true,
  };
}


// ============================================================
// DIRECT REACHABILITY
// ============================================================
//
// Checks whether there is a direct allow edge:
//
//     source ─────────> destination
//
// ============================================================

function isDirectlyReachable(
  graph,
  source,
  destination
) {

  const validation =
    validateEndpoints(
      graph,
      source,
      destination
    );

  if (!validation.valid) {

    return {
      reachable: false,
      source,
      destination,
      path: [],
      reason: validation.error,
    };

  }


  // Check whether an edge exists

  if (!graph.hasEdge(source, destination)) {

    return {
      reachable: false,
      source,
      destination,
      path: [],
      reason: "No allowed connection exists.",
    };

  }


  // Get edge information

  const edge =
    graph.edge(
      source,
      destination
    );

  const attributes =
    graph.getEdgeAttributes(edge);


  // Make sure edge represents an allowed path

  if (attributes.reachable !== true) {

    return {
      reachable: false,
      source,
      destination,
      path: [],
      reason: "Connection is not allowed.",
    };

  }


  return {

    reachable: true,

    source,

    destination,

    path: [
      source,
      destination,
    ],

    rules:
      attributes.rules || [],

  };
}


// ============================================================
// MULTI-HOP REACHABILITY
// ============================================================
//
// Uses Breadth First Search.
//
// Example:
//
//     A → B → C → D
//
// Asking:
//
//     Can A reach D?
//
// Result:
//
//     true
//
// ============================================================

function checkReachability(
  graph,
  source,
  destination
) {

  const validation =
    validateEndpoints(
      graph,
      source,
      destination
    );

  if (!validation.valid) {

    return {
      reachable: false,
      source,
      destination,
      path: [],
      reason: validation.error,
    };

  }


  // Source and destination are identical

  if (source === destination) {

    return {
      reachable: true,
      source,
      destination,
      path: [source],
      reason: "Source and destination are identical.",
    };

  }


  // ----------------------------------------------------------
  // BFS QUEUE
  // ----------------------------------------------------------

  const queue = [
    {
      node: source,
      path: [source],
    },
  ];


  // Keep track of visited nodes

  const visited = new Set();

  visited.add(source);


  // ----------------------------------------------------------
  // BFS
  // ----------------------------------------------------------

  while (queue.length > 0) {

    const current =
      queue.shift();

    const currentNode =
      current.node;

    const currentPath =
      current.path;


    // Get nodes that can be reached from current node

    const neighbors =
      graph.outNeighbors(
        currentNode
      );


    for (const neighbor of neighbors) {

      // Don't visit the same node twice

      if (visited.has(neighbor)) {
        continue;
      }


      // Check edge

      const edge =
        graph.edge(
          currentNode,
          neighbor
        );


      const attributes =
        graph.getEdgeAttributes(edge);


      // Only follow reachable edges

      if (
        attributes.reachable !== true
      ) {
        continue;
      }


      // Build new path

      const newPath = [
        ...currentPath,
        neighbor,
      ];


      // Destination reached

      if (neighbor === destination) {

        return {

          reachable: true,

          source,

          destination,

          path: newPath,

          rules:
            attributes.rules || [],

        };

      }


      visited.add(neighbor);


      queue.push({

        node: neighbor,

        path: newPath,

      });

    }

  }


  // ----------------------------------------------------------
  // NO PATH
  // ----------------------------------------------------------

  return {

    reachable: false,

    source,

    destination,

    path: [],

    reason:
      "No reachable path exists between source and destination.",

  };
}


// ============================================================
// CHECK SPECIFIC SERVICE
// ============================================================
//
// Example:
//
//     Source:
//         10.0.0.10
//
//     Destination:
//         10.0.1.20
//
//     Protocol:
//         tcp
//
//     Port:
//         443
//
// ============================================================

function checkServiceReachability(
  graph,
  source,
  destination,
  protocol,
  port = null
) {

  const validation =
    validateEndpoints(
      graph,
      source,
      destination
    );

  if (!validation.valid) {

    return {

      reachable: false,

      source,

      destination,

      protocol,

      port,

      reason: validation.error,

    };

  }


  // ----------------------------------------------------------
  // Find direct edge
  // ----------------------------------------------------------

  if (!graph.hasEdge(source, destination)) {

    return {

      reachable: false,

      source,

      destination,

      protocol,

      port,

      reason:
        "No allowed connection exists.",

    };

  }


  const edge =
    graph.edge(
      source,
      destination
    );

  const attributes =
    graph.getEdgeAttributes(edge);


  if (attributes.reachable !== true) {

    return {

      reachable: false,

      source,

      destination,

      protocol,

      port,

      reason:
        "Connection is not allowed.",

    };

  }


  // ----------------------------------------------------------
  // Find matching security rules
  // ----------------------------------------------------------

  const rules =
    attributes.rules || [];


  const matchingRules =
    rules.filter((rule) => {

      // Protocol must match

      if (
        rule.protocol !== protocol
      ) {

        return false;

      }


      // ICMP has no port

      if (
        protocol === "icmp"
      ) {

        return true;

      }


      // If caller didn't specify a port,
      // protocol match is enough

      if (port === null) {

        return true;

      }


      // TCP / UDP port match

      return (
        rule.destinationPort === port
      );

    });


  // ----------------------------------------------------------
  // MATCH FOUND
  // ----------------------------------------------------------

  if (matchingRules.length > 0) {

    return {

      reachable: true,

      source,

      destination,

      protocol,

      port,

      rules: matchingRules,

    };

  }


  // ----------------------------------------------------------
  // NO MATCH
  // ----------------------------------------------------------

  return {

    reachable: false,

    source,

    destination,

    protocol,

    port,

    rules: [],

    reason:
      "No matching security rule for the requested service.",

  };
}


// ============================================================
// FIND ALL DIRECTLY REACHABLE DESTINATIONS
// ============================================================

function getReachableDestinations(
  graph,
  source
) {

  if (!graph.hasNode(source)) {

    return {

      source,

      reachable: [],

      error:
        `Source not found: ${source}`,

    };

  }


  const destinations =
    graph.outNeighbors(source);


  const reachable =
    destinations
      .filter((destination) => {

        const edge =
          graph.edge(
            source,
            destination
          );

        const attributes =
          graph.getEdgeAttributes(
            edge
          );

        return (
          attributes.reachable === true
        );

      })
      .map((destination) => {

        const edge =
          graph.edge(
            source,
            destination
          );

        const attributes =
          graph.getEdgeAttributes(
            edge
          );

        return {

          destination,

          rules:
            attributes.rules || [],

        };

      });


  return {

    source,

    reachable,

  };
}


// ============================================================
// EXPORTS
// ============================================================

export {

  isDirectlyReachable,

  checkReachability,

  checkServiceReachability,

  getReachableDestinations,

};